
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20140611 (SVN rev 31)
// Fri May 10 07:16:11 GMT 2024
//----------------------------------------------------

package upl;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int SEMICOLON = 8;
  public static final int ELSE = 14;
  public static final int EQUAL = 28;
  public static final int THEN = 13;
  public static final int WHILE = 11;
  public static final int IDENTIFIER = 19;
  public static final int END = 3;
  public static final int GREATER_EQUAL = 27;
  public static final int GREATER = 26;
  public static final int IF = 12;
  public static final int ILLEGAL = 25;
  public static final int UNTERMINATED_CMT = 24;
  public static final int BEGIN = 2;
  public static final int DO = 10;
  public static final int LEFT_PARENTHESIS = 6;
  public static final int COMMA = 9;
  public static final int BOOL_T = 16;
  public static final int RIGHT_PARENTHESIS = 7;
  public static final int EOF = 0;
  public static final int CONST_BOOL = 18;
  public static final int ADD = 20;
  public static final int INT_T = 15;
  public static final int PRINT = 23;
  public static final int LEFT_BRACKET = 4;
  public static final int error = 1;
  public static final int ASSIGN = 22;
  public static final int CONST_INT = 17;
  public static final int MUL = 21;
  public static final int RIGHT_BRACKET = 5;
}

